### ISSUE TITLE
rake watch - not working on OSX?

### ISSUE THREAD

**Issue by jameswyse** [emorikawa/boilerstrap#2]
I've installed all the required gems, including watchr, but rake always asks me for watchr.

``` bash
James-MBA:newproject james$ rake watch
(in /Users/james/Sites/newproject)
rake aborted!
You need watchr! Install it by running `gem install watchr`
/Users/james/Sites/newproject/Rakefile:31
(See full trace by running task with --trace)

James-MBA:newproject james$ sudo gem install watchr
Successfully installed watchr-0.7
1 gem installed
Installing ri documentation for watchr-0.7...
Installing RDoc documentation for watchr-0.7...

James-MBA:newproject james$ rake watch
(in /Users/james/Sites/newproject)
rake aborted!
You need watchr! Install it by running `gem install watchr`
/Users/james/Sites/newproject/Rakefile:31
(See full trace by running task with --trace)

James-MBA:newproject james$ watchr
Usage: watchr [opts] path/to/script
```

**Comment by jameswyse** [comment]
I've upgraded ruby to the latest version, now I don't get that error. However rake watch doesn't seem to notice any changes, and produces the following notice:

`James-MBA:newproject james$ rake watch
/Users/james/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/watchr-0.7/lib/watchr.rb:111: 
Use RbConfig instead of obsolete and deprecated Config.`

**Comment by tjstein** [comment]
I get the `RbConfig` error as well:

`➜  ruby -v
ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-darwin11.3.0]`

**Comment by gabrielmancini** [comment]
same error
